GET http://127.0.0.1:5000/api/dataset

###

POST http://127.0.0.1:5000/api/predict
Content-Type: application/json

{
  "data": [
    {
      "x": 1507,
      "y": 464,
      "w": 13,
      "h": 13
    },
    {
      "x": 1507,
      "y": 464,
      "w": 13,
      "h": 13
    },
    {
      "x": 1507,
      "y": 464,
      "w": 13,
      "h": 13
    },
    {
      "x": 1507,
      "y": 464,
      "w": 13,
      "h": 13
    }
  ]
}

###
